/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as RedirectRouteImport } from './routes/redirect'
import { Route as PostsRouteImport } from './routes/posts'
import { Route as DeferredRouteImport } from './routes/deferred'
import { Route as CustomScriptDotjsRouteImport } from './routes/customScript[.]js'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users.index'
import { Route as PostsIndexRouteImport } from './routes/posts.index'
import { Route as UsersUserIdRouteImport } from './routes/users.$userId'
import { Route as PostsPostIdRouteImport } from './routes/posts.$postId'
import { Route as BoopPathlessLayoutRouteImport } from './routes/boop/_pathlessLayout'
import { Route as BeepPathlessLayoutRouteImport } from './routes/beep/_pathlessLayout'
import { Route as ApiUsersRouteImport } from './routes/api/users'
import { Route as PostsPostIdDeepRouteImport } from './routes/posts_.$postId.deep'
import { Route as BoopPathlessLayoutNestedLayoutRouteImport } from './routes/boop/_pathlessLayout/_nested-layout'
import { Route as BeepPathlessLayoutNestedLayoutRouteImport } from './routes/beep/_pathlessLayout/_nested-layout'
import { Route as ApiUsersUserIdRouteImport } from './routes/api/users.$userId'
import { Route as BoopPathlessLayoutNestedLayoutRouteRouteImport } from './routes/boop/_pathlessLayout/_nested-layout/route'
import { Route as BeepPathlessLayoutNestedLayoutIndexRouteImport } from './routes/beep/_pathlessLayout/_nested-layout/index'
import { Route as BoopPathlessLayoutNestedLayoutRouteBRouteImport } from './routes/boop/_pathlessLayout/_nested-layout/route-b'
import { Route as BoopPathlessLayoutNestedLayoutRouteARouteImport } from './routes/boop/_pathlessLayout/_nested-layout/route-a'
import { Route as BeepPathlessLayoutNestedLayoutRouteBRouteImport } from './routes/beep/_pathlessLayout/_nested-layout/route-b'
import { Route as BeepPathlessLayoutNestedLayoutRouteARouteImport } from './routes/beep/_pathlessLayout/_nested-layout/route-a'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const RedirectRoute = RedirectRouteImport.update({
  id: '/redirect',
  path: '/redirect',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsRoute = PostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const DeferredRoute = DeferredRouteImport.update({
  id: '/deferred',
  path: '/deferred',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomScriptDotjsRoute = CustomScriptDotjsRouteImport.update({
  id: '/customScript.js',
  path: '/customScript.js',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UsersRoute,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PostsRoute,
} as any)
const UsersUserIdRoute = UsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => UsersRoute,
} as any)
const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => PostsRoute,
} as any)
const BoopPathlessLayoutRoute = BoopPathlessLayoutRouteImport.update({
  id: '/boop/_pathlessLayout',
  path: '/boop',
  getParentRoute: () => rootRouteImport,
} as any)
const BeepPathlessLayoutRoute = BeepPathlessLayoutRouteImport.update({
  id: '/beep/_pathlessLayout',
  path: '/beep',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersRoute = ApiUsersRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsPostIdDeepRoute = PostsPostIdDeepRouteImport.update({
  id: '/posts_/$postId/deep',
  path: '/posts/$postId/deep',
  getParentRoute: () => rootRouteImport,
} as any)
const BoopPathlessLayoutNestedLayoutRoute =
  BoopPathlessLayoutNestedLayoutRouteImport.update({
    id: '/_nested-layout',
    getParentRoute: () => BoopPathlessLayoutRoute,
  } as any)
const BeepPathlessLayoutNestedLayoutRoute =
  BeepPathlessLayoutNestedLayoutRouteImport.update({
    id: '/_nested-layout',
    getParentRoute: () => BeepPathlessLayoutRoute,
  } as any)
const ApiUsersUserIdRoute = ApiUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => ApiUsersRoute,
} as any)
const BoopPathlessLayoutNestedLayoutRouteRoute =
  BoopPathlessLayoutNestedLayoutRouteRouteImport.update({
    id: '/_nested-layout',
    getParentRoute: () => BoopPathlessLayoutRoute,
  } as any)
const BeepPathlessLayoutNestedLayoutIndexRoute =
  BeepPathlessLayoutNestedLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => BeepPathlessLayoutNestedLayoutRoute,
  } as any)
const BoopPathlessLayoutNestedLayoutRouteBRoute =
  BoopPathlessLayoutNestedLayoutRouteBRouteImport.update({
    id: '/route-b',
    path: '/route-b',
    getParentRoute: () => BoopPathlessLayoutNestedLayoutRoute,
  } as any)
const BoopPathlessLayoutNestedLayoutRouteARoute =
  BoopPathlessLayoutNestedLayoutRouteARouteImport.update({
    id: '/route-a',
    path: '/route-a',
    getParentRoute: () => BoopPathlessLayoutNestedLayoutRoute,
  } as any)
const BeepPathlessLayoutNestedLayoutRouteBRoute =
  BeepPathlessLayoutNestedLayoutRouteBRouteImport.update({
    id: '/route-b',
    path: '/route-b',
    getParentRoute: () => BeepPathlessLayoutNestedLayoutRoute,
  } as any)
const BeepPathlessLayoutNestedLayoutRouteARoute =
  BeepPathlessLayoutNestedLayoutRouteARouteImport.update({
    id: '/route-a',
    path: '/route-a',
    getParentRoute: () => BeepPathlessLayoutNestedLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customScript.js': typeof CustomScriptDotjsRoute
  '/deferred': typeof DeferredRoute
  '/posts': typeof PostsRouteWithChildren
  '/redirect': typeof RedirectRoute
  '/users': typeof UsersRouteWithChildren
  '/api/users': typeof ApiUsersRouteWithChildren
  '/beep': typeof BeepPathlessLayoutNestedLayoutRouteWithChildren
  '/boop': typeof BoopPathlessLayoutNestedLayoutRouteWithChildren
  '/posts/$postId': typeof PostsPostIdRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/posts/': typeof PostsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/api/users/$userId': typeof ApiUsersUserIdRoute
  '/posts/$postId/deep': typeof PostsPostIdDeepRoute
  '/beep/route-a': typeof BeepPathlessLayoutNestedLayoutRouteARoute
  '/beep/route-b': typeof BeepPathlessLayoutNestedLayoutRouteBRoute
  '/boop/route-a': typeof BoopPathlessLayoutNestedLayoutRouteARoute
  '/boop/route-b': typeof BoopPathlessLayoutNestedLayoutRouteBRoute
  '/beep/': typeof BeepPathlessLayoutNestedLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customScript.js': typeof CustomScriptDotjsRoute
  '/deferred': typeof DeferredRoute
  '/redirect': typeof RedirectRoute
  '/api/users': typeof ApiUsersRouteWithChildren
  '/beep': typeof BeepPathlessLayoutNestedLayoutIndexRoute
  '/boop': typeof BoopPathlessLayoutNestedLayoutRouteWithChildren
  '/posts/$postId': typeof PostsPostIdRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/posts': typeof PostsIndexRoute
  '/users': typeof UsersIndexRoute
  '/api/users/$userId': typeof ApiUsersUserIdRoute
  '/posts/$postId/deep': typeof PostsPostIdDeepRoute
  '/beep/route-a': typeof BeepPathlessLayoutNestedLayoutRouteARoute
  '/beep/route-b': typeof BeepPathlessLayoutNestedLayoutRouteBRoute
  '/boop/route-a': typeof BoopPathlessLayoutNestedLayoutRouteARoute
  '/boop/route-b': typeof BoopPathlessLayoutNestedLayoutRouteBRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customScript.js': typeof CustomScriptDotjsRoute
  '/deferred': typeof DeferredRoute
  '/posts': typeof PostsRouteWithChildren
  '/redirect': typeof RedirectRoute
  '/users': typeof UsersRouteWithChildren
  '/api/users': typeof ApiUsersRouteWithChildren
  '/beep/_pathlessLayout': typeof BeepPathlessLayoutRouteWithChildren
  '/boop/_pathlessLayout': typeof BoopPathlessLayoutRouteWithChildren
  '/posts/$postId': typeof PostsPostIdRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/posts/': typeof PostsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/boop/_pathlessLayout/_nested-layout': typeof BoopPathlessLayoutNestedLayoutRouteWithChildren
  '/api/users/$userId': typeof ApiUsersUserIdRoute
  '/beep/_pathlessLayout/_nested-layout': typeof BeepPathlessLayoutNestedLayoutRouteWithChildren
  '/posts_/$postId/deep': typeof PostsPostIdDeepRoute
  '/beep/_pathlessLayout/_nested-layout/route-a': typeof BeepPathlessLayoutNestedLayoutRouteARoute
  '/beep/_pathlessLayout/_nested-layout/route-b': typeof BeepPathlessLayoutNestedLayoutRouteBRoute
  '/boop/_pathlessLayout/_nested-layout/route-a': typeof BoopPathlessLayoutNestedLayoutRouteARoute
  '/boop/_pathlessLayout/_nested-layout/route-b': typeof BoopPathlessLayoutNestedLayoutRouteBRoute
  '/beep/_pathlessLayout/_nested-layout/': typeof BeepPathlessLayoutNestedLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customScript.js'
    | '/deferred'
    | '/posts'
    | '/redirect'
    | '/users'
    | '/api/users'
    | '/beep'
    | '/boop'
    | '/posts/$postId'
    | '/users/$userId'
    | '/posts/'
    | '/users/'
    | '/api/users/$userId'
    | '/posts/$postId/deep'
    | '/beep/route-a'
    | '/beep/route-b'
    | '/boop/route-a'
    | '/boop/route-b'
    | '/beep/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customScript.js'
    | '/deferred'
    | '/redirect'
    | '/api/users'
    | '/beep'
    | '/boop'
    | '/posts/$postId'
    | '/users/$userId'
    | '/posts'
    | '/users'
    | '/api/users/$userId'
    | '/posts/$postId/deep'
    | '/beep/route-a'
    | '/beep/route-b'
    | '/boop/route-a'
    | '/boop/route-b'
  id:
    | '__root__'
    | '/'
    | '/customScript.js'
    | '/deferred'
    | '/posts'
    | '/redirect'
    | '/users'
    | '/api/users'
    | '/beep/_pathlessLayout'
    | '/boop/_pathlessLayout'
    | '/posts/$postId'
    | '/users/$userId'
    | '/posts/'
    | '/users/'
    | '/boop/_pathlessLayout/_nested-layout'
    | '/api/users/$userId'
    | '/beep/_pathlessLayout/_nested-layout'
    | '/posts_/$postId/deep'
    | '/beep/_pathlessLayout/_nested-layout/route-a'
    | '/beep/_pathlessLayout/_nested-layout/route-b'
    | '/boop/_pathlessLayout/_nested-layout/route-a'
    | '/boop/_pathlessLayout/_nested-layout/route-b'
    | '/beep/_pathlessLayout/_nested-layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomScriptDotjsRoute: typeof CustomScriptDotjsRoute
  DeferredRoute: typeof DeferredRoute
  PostsRoute: typeof PostsRouteWithChildren
  RedirectRoute: typeof RedirectRoute
  UsersRoute: typeof UsersRouteWithChildren
  ApiUsersRoute: typeof ApiUsersRouteWithChildren
  BeepPathlessLayoutRoute: typeof BeepPathlessLayoutRouteWithChildren
  BoopPathlessLayoutRoute: typeof BoopPathlessLayoutRouteWithChildren
  PostsPostIdDeepRoute: typeof PostsPostIdDeepRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redirect': {
      id: '/redirect'
      path: '/redirect'
      fullPath: '/redirect'
      preLoaderRoute: typeof RedirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deferred': {
      id: '/deferred'
      path: '/deferred'
      fullPath: '/deferred'
      preLoaderRoute: typeof DeferredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customScript.js': {
      id: '/customScript.js'
      path: '/customScript.js'
      fullPath: '/customScript.js'
      preLoaderRoute: typeof CustomScriptDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof UsersRoute
    }
    '/posts/': {
      id: '/posts/'
      path: '/'
      fullPath: '/posts/'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof PostsRoute
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdRouteImport
      parentRoute: typeof UsersRoute
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdRouteImport
      parentRoute: typeof PostsRoute
    }
    '/boop/_pathlessLayout': {
      id: '/boop/_pathlessLayout'
      path: '/boop'
      fullPath: '/boop'
      preLoaderRoute: typeof BoopPathlessLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beep/_pathlessLayout': {
      id: '/beep/_pathlessLayout'
      path: '/beep'
      fullPath: '/beep'
      preLoaderRoute: typeof BeepPathlessLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts_/$postId/deep': {
      id: '/posts_/$postId/deep'
      path: '/posts/$postId/deep'
      fullPath: '/posts/$postId/deep'
      preLoaderRoute: typeof PostsPostIdDeepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boop/_pathlessLayout/_nested-layout': {
      id: '/boop/_pathlessLayout/_nested-layout'
      path: ''
      fullPath: '/boop'
      preLoaderRoute: typeof BoopPathlessLayoutNestedLayoutRouteImport
      parentRoute: typeof BoopPathlessLayoutRoute
    }
    '/beep/_pathlessLayout/_nested-layout': {
      id: '/beep/_pathlessLayout/_nested-layout'
      path: ''
      fullPath: '/beep'
      preLoaderRoute: typeof BeepPathlessLayoutNestedLayoutRouteImport
      parentRoute: typeof BeepPathlessLayoutRoute
    }
    '/api/users/$userId': {
      id: '/api/users/$userId'
      path: '/$userId'
      fullPath: '/api/users/$userId'
      preLoaderRoute: typeof ApiUsersUserIdRouteImport
      parentRoute: typeof ApiUsersRoute
    }
    '/boop/_pathlessLayout/_nested-layout': {
      id: '/boop/_pathlessLayout/_nested-layout'
      path: ''
      fullPath: '/boop'
      preLoaderRoute: typeof BoopPathlessLayoutNestedLayoutRouteRouteImport
      parentRoute: typeof BoopPathlessLayoutRoute
    }
    '/beep/_pathlessLayout/_nested-layout/': {
      id: '/beep/_pathlessLayout/_nested-layout/'
      path: '/'
      fullPath: '/beep/'
      preLoaderRoute: typeof BeepPathlessLayoutNestedLayoutIndexRouteImport
      parentRoute: typeof BeepPathlessLayoutNestedLayoutRoute
    }
    '/boop/_pathlessLayout/_nested-layout/route-b': {
      id: '/boop/_pathlessLayout/_nested-layout/route-b'
      path: '/route-b'
      fullPath: '/boop/route-b'
      preLoaderRoute: typeof BoopPathlessLayoutNestedLayoutRouteBRouteImport
      parentRoute: typeof BoopPathlessLayoutNestedLayoutRoute
    }
    '/boop/_pathlessLayout/_nested-layout/route-a': {
      id: '/boop/_pathlessLayout/_nested-layout/route-a'
      path: '/route-a'
      fullPath: '/boop/route-a'
      preLoaderRoute: typeof BoopPathlessLayoutNestedLayoutRouteARouteImport
      parentRoute: typeof BoopPathlessLayoutNestedLayoutRoute
    }
    '/beep/_pathlessLayout/_nested-layout/route-b': {
      id: '/beep/_pathlessLayout/_nested-layout/route-b'
      path: '/route-b'
      fullPath: '/beep/route-b'
      preLoaderRoute: typeof BeepPathlessLayoutNestedLayoutRouteBRouteImport
      parentRoute: typeof BeepPathlessLayoutNestedLayoutRoute
    }
    '/beep/_pathlessLayout/_nested-layout/route-a': {
      id: '/beep/_pathlessLayout/_nested-layout/route-a'
      path: '/route-a'
      fullPath: '/beep/route-a'
      preLoaderRoute: typeof BeepPathlessLayoutNestedLayoutRouteARouteImport
      parentRoute: typeof BeepPathlessLayoutNestedLayoutRoute
    }
  }
}

interface PostsRouteChildren {
  PostsPostIdRoute: typeof PostsPostIdRoute
  PostsIndexRoute: typeof PostsIndexRoute
}

const PostsRouteChildren: PostsRouteChildren = {
  PostsPostIdRoute: PostsPostIdRoute,
  PostsIndexRoute: PostsIndexRoute,
}

const PostsRouteWithChildren = PostsRoute._addFileChildren(PostsRouteChildren)

interface UsersRouteChildren {
  UsersUserIdRoute: typeof UsersUserIdRoute
  UsersIndexRoute: typeof UsersIndexRoute
}

const UsersRouteChildren: UsersRouteChildren = {
  UsersUserIdRoute: UsersUserIdRoute,
  UsersIndexRoute: UsersIndexRoute,
}

const UsersRouteWithChildren = UsersRoute._addFileChildren(UsersRouteChildren)

interface ApiUsersRouteChildren {
  ApiUsersUserIdRoute: typeof ApiUsersUserIdRoute
}

const ApiUsersRouteChildren: ApiUsersRouteChildren = {
  ApiUsersUserIdRoute: ApiUsersUserIdRoute,
}

const ApiUsersRouteWithChildren = ApiUsersRoute._addFileChildren(
  ApiUsersRouteChildren,
)

interface BeepPathlessLayoutNestedLayoutRouteChildren {
  BeepPathlessLayoutNestedLayoutRouteARoute: typeof BeepPathlessLayoutNestedLayoutRouteARoute
  BeepPathlessLayoutNestedLayoutRouteBRoute: typeof BeepPathlessLayoutNestedLayoutRouteBRoute
  BeepPathlessLayoutNestedLayoutIndexRoute: typeof BeepPathlessLayoutNestedLayoutIndexRoute
}

const BeepPathlessLayoutNestedLayoutRouteChildren: BeepPathlessLayoutNestedLayoutRouteChildren =
  {
    BeepPathlessLayoutNestedLayoutRouteARoute:
      BeepPathlessLayoutNestedLayoutRouteARoute,
    BeepPathlessLayoutNestedLayoutRouteBRoute:
      BeepPathlessLayoutNestedLayoutRouteBRoute,
    BeepPathlessLayoutNestedLayoutIndexRoute:
      BeepPathlessLayoutNestedLayoutIndexRoute,
  }

const BeepPathlessLayoutNestedLayoutRouteWithChildren =
  BeepPathlessLayoutNestedLayoutRoute._addFileChildren(
    BeepPathlessLayoutNestedLayoutRouteChildren,
  )

interface BeepPathlessLayoutRouteChildren {
  BeepPathlessLayoutNestedLayoutRoute: typeof BeepPathlessLayoutNestedLayoutRouteWithChildren
}

const BeepPathlessLayoutRouteChildren: BeepPathlessLayoutRouteChildren = {
  BeepPathlessLayoutNestedLayoutRoute:
    BeepPathlessLayoutNestedLayoutRouteWithChildren,
}

const BeepPathlessLayoutRouteWithChildren =
  BeepPathlessLayoutRoute._addFileChildren(BeepPathlessLayoutRouteChildren)

interface BoopPathlessLayoutNestedLayoutRouteChildren {
  BoopPathlessLayoutNestedLayoutRouteARoute: typeof BoopPathlessLayoutNestedLayoutRouteARoute
  BoopPathlessLayoutNestedLayoutRouteBRoute: typeof BoopPathlessLayoutNestedLayoutRouteBRoute
}

const BoopPathlessLayoutNestedLayoutRouteChildren: BoopPathlessLayoutNestedLayoutRouteChildren =
  {
    BoopPathlessLayoutNestedLayoutRouteARoute:
      BoopPathlessLayoutNestedLayoutRouteARoute,
    BoopPathlessLayoutNestedLayoutRouteBRoute:
      BoopPathlessLayoutNestedLayoutRouteBRoute,
  }

const BoopPathlessLayoutNestedLayoutRouteWithChildren =
  BoopPathlessLayoutNestedLayoutRoute._addFileChildren(
    BoopPathlessLayoutNestedLayoutRouteChildren,
  )

interface BoopPathlessLayoutRouteChildren {
  BoopPathlessLayoutNestedLayoutRouteRoute: typeof BoopPathlessLayoutNestedLayoutRouteRoute
  BoopPathlessLayoutNestedLayoutRoute: typeof BoopPathlessLayoutNestedLayoutRouteWithChildren
}

const BoopPathlessLayoutRouteChildren: BoopPathlessLayoutRouteChildren = {
  BoopPathlessLayoutNestedLayoutRouteRoute:
    BoopPathlessLayoutNestedLayoutRouteRoute,
  BoopPathlessLayoutNestedLayoutRoute:
    BoopPathlessLayoutNestedLayoutRouteWithChildren,
}

const BoopPathlessLayoutRouteWithChildren =
  BoopPathlessLayoutRoute._addFileChildren(BoopPathlessLayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomScriptDotjsRoute: CustomScriptDotjsRoute,
  DeferredRoute: DeferredRoute,
  PostsRoute: PostsRouteWithChildren,
  RedirectRoute: RedirectRoute,
  UsersRoute: UsersRouteWithChildren,
  ApiUsersRoute: ApiUsersRouteWithChildren,
  BeepPathlessLayoutRoute: BeepPathlessLayoutRouteWithChildren,
  BoopPathlessLayoutRoute: BoopPathlessLayoutRouteWithChildren,
  PostsPostIdDeepRoute: PostsPostIdDeepRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
